###
POST http://localhost:3000/api/crear_usuario HTTP/1.1
Content-Type: application/json

{
    "nombreUsuario":"eren345",
    "nombre":"juan carlos perez",
    "contraseña":"jcarlos222"
}

###
GET http://localhost:3000/api/usuarios HTTP/1.1

###
GET http://localhost:3000/api/usuarios/64b23a74fcf1dcaa568a09b1 HTTP/1.1

###
GET http://localhost:3000/api/usuarios/inuyasha98 HTTP/1.1

###
PUT http://localhost:3000/api/actualizar_usuario/64b58659dede517d035a8cde HTTP/1.1
Content-Type: application/json

{
    "nombreUsuario": "dante234",
    "nombre": "juan enrique lara",
    "contraseña": "123456"
}

###
DELETE http://localhost:3000/api/eliminar_usuario/64b2356f6ac9ded90fe5593a

// egresos ------------------------------------------------------------------------------
###
POST http://localhost:3000/api/crear_egreso HTTP/1.1
Content-Type: application/json

{
    "idUsuario": "64b2356f6ac9ded90fe5593a",
    "cantidad": 1
}

###
GET http://localhost:3000/api/egresos HTTP/1.1

###
GET http://localhost:3000/api/egresos/64b573803faf7a62c71ef032 HTTP/1.1

###
PUT http://localhost:3000/api/actualizar_egreso/64b80d34ef0c7309f827ef1d HTTP/1.1
Content-Type: application/json

{
    "idUsuario": "64b2356f6ac9ded90fe5593a",
    "cantidad": 120.90
}

### 
DELETE http://localhost:3000/api/eliminar_egreso/64b80d34ef0c7309f827ef1d HTTP/1.1

// productos ------------------------------------------------------------------
###
POST http://localhost:3000/api/crear_producto HTTP/1.1
Content-Type: application/json

{
    "nombre":"mkmkmkm",
    "tipo":"bbbbb",
    "precio": 3.50
}

###
GET http://localhost:3000/api/productos HTTP/1.1

###
GET http://localhost:3000/api/productos/64b6e12f1c43be153a7113ba HTTP/1.1

###
GET http://localhost:3000/api/productos/lll HTTP/1.1

###
PUT http://localhost:3000/api/actualizar_producto/64b5a4810b9bd012e06f4f55 HTTP/1.1
Content-Type: application/json

{
    "nombre":"qwert",
    "tipo":"mnbv",
    "precio": 777
}

###
DELETE http://localhost:3000/api/eliminar_producto/64b5a4810b9bd012e06f4f55 HTTP/1.1

// ventas -------------------------------------------------------------------
###
POST http://localhost:3000/api/crear_venta HTTP/1.1
Content-Type: application/json

{
    "productos":["aa","bb","cc"],
    "total": 9.7
}

###
GET http://localhost:3000/api/ventas HTTP/1.1

###
GET http://localhost:3000/api/ventas/64b6efec2fb39c03840f7b25 HTTP/1.1

###
PUT http://localhost:3000/api/actualizar_venta/64b6efec2fb39c03840f7b25 HTTP/1.1
Content-Type: application/json

{
    "productos":["hola","como","esta","usted"],
    "total": 123.67
}

### 
DELETE http://localhost:3000/api/eliminar_venta/64b6f0622fb39c03840f7b27 HTTP/1.1

// ingresos ----------------------------------------------
###
POST http://localhost:3000/api/crear_ingreso HTTP/1.1
Content-Type: application/json

{
    "cantidad": 1122
}

###
GET http://localhost:3000/api/ingresos HTTP/1.1

###
GET http://localhost:3000/api/ingresos/64b7049f61f0682247d082ce HTTP/1.1

###
PUT http://localhost:3000/api/actualizar_ingreso/64b7049f61f0682247d082ce HTTP/1.1
Content-Type: application/json

{
    "cantidad": 1234
}

###
DELETE http://localhost:3000/api/eliminar_ingreso/64b703e3eeaebb6567ddbaa6 HTTP/1.1